issue_fields = {
    "data": {
        "repository": {
            "issueFields": {
                "nodes": [
                    {
                        "__typename": "IssueFieldSingleSelect",
                        "id": "IFSS_kgDNFCk",
                        "description": "Current importance level assigned to this issue",
                        "name": "Priority",
                        "fullDatabaseId": "5161",
                        "options": [
                            {
                                "id": "IFSSO_kgDNFNU",
                                "name": "Urgent",
                                "databaseId": 5333,
                                "fullDatabaseId": "5333",
                            },
                            {
                                "id": "IFSSO_kgDNFNY",
                                "name": "High",
                                "databaseId": 5334,
                                "fullDatabaseId": "5334",
                            },
                            {
                                "id": "IFSSO_kgDNFNc",
                                "name": "Medium",
                                "databaseId": 5335,
                                "fullDatabaseId": "5335",
                            },
                            {
                                "id": "IFSSO_kgDNFNg",
                                "name": "Low",
                                "databaseId": 5336,
                                "fullDatabaseId": "5336",
                            },
                        ],
                    },
                    {
                        "__typename": "IssueFieldDate",
                        "description": "Date when work on project/epic will begin",
                        "id": "IFD_kgDNFCo",
                        "name": "Start date",
                        "fullDatabaseId": "5162",
                    },
                    {
                        "__typename": "IssueFieldDate",
                        "description": "Expected completion date for this project",
                        "id": "IFD_kgDNFCs",
                        "name": "End date",
                        "fullDatabaseId": "5163",
                    },
                    {
                        "__typename": "IssueFieldNumber",
                        "name": "DTS Estimate",
                        "description": "",
                        "dataType": "NUMBER",
                        "id": "IFN_kgDNFD0",
                        "fullDatabaseId": "5181",
                    },
                    {
                        "__typename": "IssueFieldSingleSelect",
                        "id": "IFSS_kgDNGXg",
                        "description": "Data & Technology Services team responsible for executing this work",
                        "name": "DTS Team",
                        "fullDatabaseId": "6520",
                        "options": [
                            {
                                "id": "IFSSO_kgDNH3M",
                                "name": "Apps",
                                "databaseId": 8051,
                                "fullDatabaseId": "8051",
                            },
                            {
                                "id": "IFSSO_kgDNH3Q",
                                "name": "Data Science",
                                "databaseId": 8052,
                                "fullDatabaseId": "8052",
                            },
                            {
                                "id": "IFSSO_kgDNH3U",
                                "name": "Dev",
                                "databaseId": 8053,
                                "fullDatabaseId": "8053",
                            },
                            {
                                "id": "IFSSO_kgDNH3Y",
                                "name": "ECM",
                                "databaseId": 8054,
                                "fullDatabaseId": "8054",
                            },
                            {
                                "id": "IFSSO_kgDNH3c",
                                "name": "Geo",
                                "databaseId": 8055,
                                "fullDatabaseId": "8055",
                            },
                            {
                                "id": "IFSSO_kgDNH3g",
                                "name": "Maximo",
                                "databaseId": 8056,
                                "fullDatabaseId": "8056",
                            },
                            {
                                "id": "IFSSO_kgDNH3o",
                                "name": "Tech Services",
                                "databaseId": 8058,
                                "fullDatabaseId": "8058",
                            },
                            {
                                "id": "IFSSO_kgDNH3k",
                                "name": "Product",
                                "databaseId": 8057,
                                "fullDatabaseId": "8057",
                            },
                            {
                                "id": "IFSSO_kgDNH3s",
                                "name": "[Operations]",
                                "databaseId": 8059,
                                "fullDatabaseId": "8059",
                            },
                        ],
                    },
                    {
                        "__typename": "IssueFieldSingleSelect",
                        "id": "IFSS_kgDNJ70",
                        "description": "Transportation Public Works Division ",
                        "name": "TPW Division",
                        "fullDatabaseId": "10173",
                        "options": [
                            {
                                "id": "IFSSO_kgDNOE8",
                                "name": "Admin",
                                "databaseId": 14415,
                                "fullDatabaseId": "14415",
                            },
                            {
                                "id": "IFSSO_kgDNOFA",
                                "name": "AMD",
                                "databaseId": 14416,
                                "fullDatabaseId": "14416",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcIg",
                                "name": "ATSD",
                                "databaseId": 154658,
                                "fullDatabaseId": "154658",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcIw",
                                "name": "CCG",
                                "databaseId": 154659,
                                "fullDatabaseId": "154659",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcJA",
                                "name": "CSD",
                                "databaseId": 154660,
                                "fullDatabaseId": "154660",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcJQ",
                                "name": "DM",
                                "databaseId": 154661,
                                "fullDatabaseId": "154661",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcJg",
                                "name": "DTS",
                                "databaseId": 154662,
                                "fullDatabaseId": "154662",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcJw",
                                "name": "EM",
                                "databaseId": 154663,
                                "fullDatabaseId": "154663",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcKA",
                                "name": "Equity",
                                "databaseId": 154664,
                                "fullDatabaseId": "154664",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcKQ",
                                "name": "Finance",
                                "databaseId": 154665,
                                "fullDatabaseId": "154665",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcKg",
                                "name": "HR",
                                "databaseId": 154666,
                                "fullDatabaseId": "154666",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcKw",
                                "name": "LA",
                                "databaseId": 154667,
                                "fullDatabaseId": "154667",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcLA",
                                "name": "LDE",
                                "databaseId": 154668,
                                "fullDatabaseId": "154668",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcLQ",
                                "name": "Logistics",
                                "databaseId": 154669,
                                "fullDatabaseId": "154669",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcLg",
                                "name": "OCE",
                                "databaseId": 154670,
                                "fullDatabaseId": "154670",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcLw",
                                "name": "OPM",
                                "databaseId": 154671,
                                "fullDatabaseId": "154671",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcMA",
                                "name": "OSE",
                                "databaseId": 154672,
                                "fullDatabaseId": "154672",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcMQ",
                                "name": "PD",
                                "databaseId": 154673,
                                "fullDatabaseId": "154673",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcMg",
                                "name": "PE",
                                "databaseId": 154674,
                                "fullDatabaseId": "154674",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcMw",
                                "name": "PIO",
                                "databaseId": 154675,
                                "fullDatabaseId": "154675",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcNA",
                                "name": "PO",
                                "databaseId": 154676,
                                "fullDatabaseId": "154676",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcNQ",
                                "name": "ROW",
                                "databaseId": 154677,
                                "fullDatabaseId": "154677",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcNg",
                                "name": "SBO",
                                "databaseId": 154678,
                                "fullDatabaseId": "154678",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcNw",
                                "name": "SDD",
                                "databaseId": 154679,
                                "fullDatabaseId": "154679",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcOA",
                                "name": "SMD",
                                "databaseId": 154680,
                                "fullDatabaseId": "154680",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcOQ",
                                "name": "SMP",
                                "databaseId": 154681,
                                "fullDatabaseId": "154681",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcOg",
                                "name": "SP",
                                "databaseId": 154682,
                                "fullDatabaseId": "154682",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcOw",
                                "name": "SUTD",
                                "databaseId": 154683,
                                "fullDatabaseId": "154683",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcPA",
                                "name": "TDS",
                                "databaseId": 154684,
                                "fullDatabaseId": "154684",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcPQ",
                                "name": "TED",
                                "databaseId": 154685,
                                "fullDatabaseId": "154685",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcPg",
                                "name": "UF",
                                "databaseId": 154686,
                                "fullDatabaseId": "154686",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcPw",
                                "name": "US",
                                "databaseId": 154687,
                                "fullDatabaseId": "154687",
                            },
                            {
                                "id": "IFSSO_kgDOAAJcQA",
                                "name": "VZ",
                                "databaseId": 154688,
                                "fullDatabaseId": "154688",
                            },
                            {
                                "id": "IFSSO_kgDOBGoLlg",
                                "name": "TPW",
                                "databaseId": 74058646,
                                "fullDatabaseId": "74058646",
                            },
                        ],
                    },
                    {
                        "__typename": "IssueFieldSingleSelect",
                        "id": "IFSS_kgDNJ_I",
                        "description": "Standardized, cross-team status",
                        "name": "DTS Status",
                        "fullDatabaseId": "10226",
                        "options": [
                            {
                                "id": "IFSSO_kgDNOPE",
                                "name": "New",
                                "databaseId": 14577,
                                "fullDatabaseId": "14577",
                            },
                            {
                                "id": "IFSSO_kgDNOPM",
                                "name": "Needs Scoping",
                                "databaseId": 14579,
                                "fullDatabaseId": "14579",
                            },
                            {
                                "id": "IFSSO_kgDNOPQ",
                                "name": "Backlog",
                                "databaseId": 14580,
                                "fullDatabaseId": "14580",
                            },
                            {
                                "id": "IFSSO_kgDNOPU",
                                "name": "On Deck",
                                "databaseId": 14581,
                                "fullDatabaseId": "14581",
                            },
                            {
                                "id": "IFSSO_kgDNOPY",
                                "name": "In Progress",
                                "databaseId": 14582,
                                "fullDatabaseId": "14582",
                            },
                            {
                                "id": "IFSSO_kgDNOPg",
                                "name": "Review/QA",
                                "databaseId": 14584,
                                "fullDatabaseId": "14584",
                            },
                            {
                                "id": "IFSSO_kgDNOPc",
                                "name": "Blocked",
                                "databaseId": 14583,
                                "fullDatabaseId": "14583",
                            },
                            {
                                "id": "IFSSO_kgDNOPo",
                                "name": "Complete",
                                "databaseId": 14586,
                                "fullDatabaseId": "14586",
                            },
                            {
                                "id": "IFSSO_kgDOBGoLHg",
                                "name": "Ongoing",
                                "databaseId": 74058526,
                                "fullDatabaseId": "74058526",
                            },
                            {
                                "id": "IFSSO_kgDNOPI",
                                "name": "Icebox",
                                "databaseId": 14578,
                                "fullDatabaseId": "14578",
                            },
                        ],
                    },
                    {
                        "__typename": "IssueFieldText",
                        "name": "DTS Description",
                        "id": "IFT_kgDOApCswg",
                        "description": "High-level explanation of a Product, Project or Service",
                        "fullDatabaseId": "43035842",
                    },
                ]
            }
        }
    }
}
