zenhub_pipeline_ids = [
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTQ3NTE", "name": "New"},
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTQ4MTE", "name": "Icebox"},
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTQ4Njk", "name": "Needs Scoping"},
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTQ5MjA", "name": "Backlog"},
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTQ5ODM", "name": "On Deck"},
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTUwODg", "name": "In Progress"},
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTUxNDY", "name": "Ongoing"},
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTUwMzI", "name": "Blocked"},
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTUxOTk", "name": "Review/QA"},
    {"id": "Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NTUyNjk", "name": "Ready to Deploy"},
]

# These are retrieved using the gh_projects_fields_query in queries.py
github_project_board_ids = {
    "Geo": {
        "board_id": 6,
        "board_node_id": "PVT_kwDOAEpV4M4BBib3",
        "estimate_field_id": "PVTF_lADOAEpV4M4BBib3zg0A61c",
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BBib3zg0A604",
            "options": {
                "New": "5363d18e",
                "Icebox": "63604d86",
                "Needs Scoping": "f75ad846",
                "Backlog": "47fc9ee4",
                "On Deck": "4f87863e",
                "In Progress": "9448cc97",
                "Blocked": "e4848f40",
                "Review/QA": "37e3d819",
                "Ongoing": "0555309e",
                "Closed": "98236657",
            },
        },
    },
    "Product": {
        "board_id": 23,
        "board_node_id": "PVT_kwDOAEpV4M4BNi8O",
        "estimate_field_id": "PVTF_lADOAEpV4M4BNi8Ozg8glL4",
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BNi8Ozg8glLM",
            "options": {
                "New": "f75ad846",
                "Icebox": "18d97bf9",
                "Needs Scoping": "097d0a77",
                "Backlog": "4691a96f",
                "On Deck": "16f0a892",
                "In Progress": "47fc9ee4",
                "Blocked": "70cb9b96",
                "Review/QA": "d888407f",
                "Ongoing": "e6ad5fff",
                "Closed": "98236657",
            },
        },
    },
    "Enterprise Case Management": {
        "board_id": 22,
        "board_node_id": "PVT_kwDOAEpV4M4BMtoV",
        "estimate_field_id": "PVTF_lADOAEpV4M4BMtoVzg76vPs",
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BMtoVzg76vPI",
            "options": {
                "New": "5363d18e",
                "Icebox": "63604d86",
                "Needs Scoping": "f75ad846",
                "Backlog": "47fc9ee4",
                "On Deck": "4f87863e",
                "In Progress": "9448cc97",
                "Blocked": "e4848f40",
                "Review/QA": "37e3d819",
                "Ready to Deploy": "1fa3533a",
                "Ongoing": "0555309e",
                "Closed": "98236657",
            },
        },
    },
    "Tech Services": {
        "board_id": 21,
        "board_node_id": "PVT_kwDOAEpV4M4BMtnX",
        "estimate_field_id": None,  # I couldn't find any estimate field for this board.
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BMtnXzg76uj8",
            "options": {
                "New": "a0a9b546",
                "Icebox": "9dc31185",
                "Needs Scoping": "f75ad846",
                "Backlog": "3c0b3ea7",
                "On Deck": "889c9c26",
                "In Progress": "47fc9ee4",
                "Blocked": "d6084e23",
                "Review QA": "467db1fa",
                "Ongoing": "7119f4f2",
                "Closed": "98236657",
            },
        },
    },
    "DTS Operations": {
        "board_id": 20,
        "board_node_id": "PVT_kwDOAEpV4M4BMnDw",
        "estimate_field_id": None,  # I couldn't find any estimate field for this board.
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BMnDwzg72BBY",
            "options": {
                "New": "1726fb16",
                "Icebox": "5fc32ef6",
                "Needs Scoping": "f75ad846",
                "Backlog": "5cac5a3d",
                "On Deck": "a9abaa36",
                "In Progress": "47fc9ee4",
                "Blocked": "bb1d76aa",
                "Review/QA": "ace3d3d7",
                "Ongoing": "6b92e247",
                "Closed": "98236657",
            },
        },
    },
    "Data Science": {
        "board_id": 19,
        "board_node_id": "PVT_kwDOAEpV4M4BMeD5",
        "estimate_field_id": "PVTF_lADOAEpV4M4BMeD5zg7viKA",
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BMeD5zg7viJc",
            "options": {
                "New": "5363d18e",
                "Icebox": "63604d86",
                "Needs Scoping": "f75ad846",
                "Backlog": "47fc9ee4",
                "On Deck": "4f87863e",
                "In Progress": "9448cc97",
                "Blocked": "e4848f40",
                "Review/QA": "37e3d819",
                "Ongoing": "0555309e",
                "Closed": "98236657",
            },
        },
    },
    "Maximo": {
        "board_id": 18,
        "board_node_id": "PVT_kwDOAEpV4M4BK01Z",
        "estimate_field_id": "PVTF_lADOAEpV4M4BK01Zzg6lLK0",
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BK01Zzg6lLIU",
            "options": {
                "New": "5363d18e",
                "Icebox": "63604d86",
                "Needs Scoping": "f75ad846",
                "Backlog": "47fc9ee4",
                "On Deck": "4f87863e",
                "In Progress": "9448cc97",
                "Blocked": "e4848f40",
                "Review/QA": "37e3d819",
                "Ongoing": "0555309e",
                "Closed": "98236657",
            },
        },
    },
    "Apps": {
        "board_id": 16,
        "board_node_id": "PVT_kwDOAEpV4M4BKUOP",
        "estimate_field_id": "PVTF_lADOAEpV4M4BKUOPzg6h1vo",
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BKUOPzg6ODvk",
            "options": {
                "New": "f75ad846",
                "Icebox": "18d97bf9",
                "Needs Scoping": "097d0a77",
                "Backlog": "4691a96f",
                "On Deck": "16f0a892",
                "In Progress": "47fc9ee4",
                "Blocked": "70cb9b96",
                "Review/QA": "d888407f",
                "Ongoing": "e6ad5fff",
                "Closed": "98236657",
            },
        },
    },
    "Vision Zero": {
        "board_id": 13,
        "board_node_id": "PVT_kwDOAEpV4M4BGXZs",
        "estimate_field_id": None,  # I couldn't find any estimate field for this board.
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BGXZszg3bwf8",
            "options": {
                "Unscoped": "a689acbb",
                "Needs scoping": "66efbe71",
                "Ready to work": "f75ad846",
                "In progress": "47fc9ee4",
                "Review/QA": "817a9eff",
                "Done": "98236657",
            },
        },
    },
    "DTS Project Portfolio": {
        "board_id": 11,
        "board_node_id": "PVT_kwDOAEpV4M4BFvqD",
        "estimate_field_id": None,  # I couldn't find any estimate field for this board.
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BFvqDzg2_jrE",
            "options": {
                "Needs Scoping": "be1bf228",
                "Backlog": "41300d65",
                "On Deck": "f75ad846",
                "In Progress": "47fc9ee4",
                "Done": "98236657",
            },
        },
    },
    "Human Resources FY2026": {
        "board_id": 10,
        "board_node_id": "PVT_kwDOAEpV4M4BFjVb",
        "estimate_field_id": "PVT_kwDOAEpV4M4BFjVb",
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BFjVbzg22wsc",
            "options": {
                "New": "5363d18e",
                "Icebox": "63604d86",
                "Needs Scoping": "f75ad846",
                "Backlog": "47fc9ee4",
                "Closed": "98236657",
                "On Deck": "4f87863e",
                "In Progress": "9448cc97",
                "Blocked": "e4848f40",
                "Review/QA": "37e3d819",
                "Ongoing": "0555309e",
            },
        },
    },
    "Parking and Community Services": {
        "board_id": 8,
        "board_node_id": "PVT_kwDOAEpV4M4BEDyD",
        "estimate_field_id": "PVTF_lADOAEpV4M4BEDyDzg1y91k",
        "pipeline_field_id": {
            "field_id": "PVTSSF_lADOAEpV4M4BEDyDzg1y91A",
            "options": {
                "New": "5363d18e",
                "Icebox": "63604d86",
                "Needs Scoping": "f75ad846",
                "Backlog": "47fc9ee4",
                "On Deck": "4f87863e",
                "In Progress": "9448cc97",
                "Blocked": "e4848f40",
                "Review/QA": "37e3d819",
                "Ongoing": "0555309e",
                "Closed": "98236657",
            },
        },
    },
    "Dev": {
        "board_id": 25,
        "board_node_id": 'PVT_kwDOAEpV4M4BOgBQ',
        "estimate_field_id": 'PVTF_lADOAEpV4M4BOgBQzg9L1Ss',
        "pipeline_field_id": {
            "field_id": 'PVTSSF_lADOAEpV4M4BOgBQzg9L1SI',
            "options": {
                "New": '5363d18e',
                "Icebox": '63604d86',
                "Needs Scoping": 'f75ad846',
                "Backlog": '47fc9ee4',
                "On Deck": '4f87863e',
                "In Progress": '9448cc97',
                "Blocked": 'e4848f40',
                "Review/QA": '37e3d819',
                "Ongoing": '0555309e',
                "Closed": '98236657',
            },
        },
    },
}
